-- MySQL Script generated by MySQL Workbench
-- Wed Sep 28 14:11:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userId` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userType` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mobile` BIGINT(12) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Package` (
  `packageId` INT NOT NULL,
  `packageName` VARCHAR(45) NOT NULL,
  `packageDescription` VARCHAR(45) NULL,
  `packageType` VARCHAR(45) NULL,
  `packageCost` INT NOT NULL,
  `paymentDetails` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`packageId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Booking` (
  `bookingId` INT NOT NULL,
  `bookingType` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `bookingTitle` VARCHAR(45) NULL,
  `bookingDate` DATE NULL,
  `Package_packageId` INT NOT NULL,
  PRIMARY KEY (`bookingId`, `Package_packageId`),
  INDEX `fk_Booking_Package_idx` (`Package_packageId` ASC) VISIBLE,
  CONSTRAINT `fk_Booking_Package`
    FOREIGN KEY (`Package_packageId`)
    REFERENCES `mydb`.`Package` (`packageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `hotelId` INT NOT NULL,
  `hotelName` VARCHAR(45) NOT NULL,
  `hotelType` VARCHAR(45) NULL,
  `hotelDescription` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `rent` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `Package_packageId` INT NOT NULL,
  PRIMARY KEY (`hotelId`, `Package_packageId`),
  INDEX `fk_Hotel_Package1_idx` (`Package_packageId` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_Package1`
    FOREIGN KEY (`Package_packageId`)
    REFERENCES `mydb`.`Package` (`packageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Travels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Travels` (
  `travelId` INT NOT NULL,
  `travelsName` VARCHAR(45) NOT NULL,
  `agentName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `contact` DOUBLE NULL,
  PRIMARY KEY (`travelId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bus` (
  `busId` INT NOT NULL,
  `busType` VARCHAR(45) NULL,
  `busNo` INT NOT NULL,
  `capacity` INT NULL,
  `Travel_travelId` INT NOT NULL,
  PRIMARY KEY (`busId`, `Travel_travelId`),
  INDEX `fk_Bus_Travel1_idx` (`Travel_travelId` ASC) VISIBLE,
  CONSTRAINT `fk_Bus_Travel1`
    FOREIGN KEY (`Travel_travelId`)
    REFERENCES `mydb`.`Travels` (`travelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Route` (
  `routeId` INT NOT NULL,
  `routeFrom` VARCHAR(45) NOT NULL,
  `routeTo` VARCHAR(45) NOT NULL,
  `departureTime` TIME NOT NULL,
  `arrivalTime` TIME NOT NULL,
  `dateOfJourney` DATE NULL,
  `pickUpPoint` VARCHAR(45) NULL,
  `fare` INT NULL,
  `Bus_busId` INT NOT NULL,
  PRIMARY KEY (`routeId`, `Bus_busId`),
  INDEX `fk_Route_Bus1_idx` (`Bus_busId` ASC) VISIBLE,
  CONSTRAINT `fk_Route_Bus1`
    FOREIGN KEY (`Bus_busId`)
    REFERENCES `mydb`.`Bus` (`busId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TicketDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TicketDetails` (
  `ticketId` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `Package_packageId` INT NOT NULL,
  `Route_routeId` INT NOT NULL,
  PRIMARY KEY (`ticketId`, `Package_packageId`, `Route_routeId`),
  INDEX `fk_Ticket_Package1_idx` (`Package_packageId` ASC) VISIBLE,
  INDEX `fk_Ticket_Route1_idx` (`Route_routeId` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Package1`
    FOREIGN KEY (`Package_packageId`)
    REFERENCES `mydb`.`Package` (`packageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Route1`
    FOREIGN KEY (`Route_routeId`)
    REFERENCES `mydb`.`Route` (`routeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Booking` (
  `User_userId` INT NOT NULL,
  `Booking_bookingId` INT NOT NULL,
  `Booking_Package_packageId` INT NOT NULL,
  PRIMARY KEY (`User_userId`, `Booking_bookingId`, `Booking_Package_packageId`),
  INDEX `fk_User_has_Booking_Booking1_idx` (`Booking_bookingId` ASC, `Booking_Package_packageId` ASC) VISIBLE,
  INDEX `fk_User_has_Booking_User1_idx` (`User_userId` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Booking_User1`
    FOREIGN KEY (`User_userId`)
    REFERENCES `mydb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Booking_Booking1`
    FOREIGN KEY (`Booking_bookingId` , `Booking_Package_packageId`)
    REFERENCES `mydb`.`Booking` (`bookingId` , `Package_packageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Report` (
  `reportId` INT NOT NULL,
  `reportName` VARCHAR(45) NULL,
  `reportType` VARCHAR(45) NULL,
  `User_userId` INT NOT NULL,
  PRIMARY KEY (`reportId`, `User_userId`),
  INDEX `fk_Report_User1_idx` (`User_userId` ASC) VISIBLE,
  CONSTRAINT `fk_Report_User1`
    FOREIGN KEY (`User_userId`)
    REFERENCES `mydb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feedback` (
  `feedbackId` INT NOT NULL,
  `feedbackString` VARCHAR(255) NULL,
  `rating` DECIMAL(5) NULL,
  `submitDate` DATE NULL,
  `User_userId` INT NOT NULL,
  PRIMARY KEY (`feedbackId`, `User_userId`),
  INDEX `fk_Feedback_User1_idx` (`User_userId` ASC) VISIBLE,
  CONSTRAINT `fk_Feedback_User1`
    FOREIGN KEY (`User_userId`)
    REFERENCES `mydb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
